# Generated by Django 5.0.1 on 2024-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_tags_tags_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(default='Plants', max_length=100),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
