# Generated by Django 5.0.1 on 2024-01-31 14:09

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cartorder_price_alter_cartorderitems_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='core.product'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=30, prefix='', unique=True),
        ),
    ]
