# Generated by Django 5.0.1 on 2024-04-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_productreview_product_alter_subcategory_sid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
