# Generated by Django 5.0.1 on 2024-04-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_cartorder_oid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='city',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='country',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='oid',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='oreder_note',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='shipping_method',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='state',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tracking_id',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='tracking_website_address',
        ),
    ]
