# Generated by Django 5.0.1 on 2024-04-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_cartorder_address_remove_cartorder_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
