# Generated by Django 5.0.1 on 2024-04-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'verbose_name_plural': 'Address'},
        ),
    ]
